name: GraysPets
version: 0.1.0
main: io.github.gabehowe.grayspets.GraysPets
api-version: 1.16
authors: [ GabrielHowe ]
description: A pets plugin for gray
commands:
  pet:
    usage: /<command> <petType|hide>
    description: ''
    permission: grayspets.pet
    permission-message: §cYou do not have permission to use that command
